version: '3.9'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: banco_estudo_spring
      TZ: America/Sao_Paulo
    ports:
      - 3308:3306
    networks:
      - spring-network

  spring-app:
    build: .
    container_name: spring-kotlin-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banco_estudo_spring?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_TOKEN_SECRET_KEY: 53cr37
      JWT_TOKEN_EXPIRE_LENGTH: 360000
    ports:
      - 8080:8080
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
