name: Continuous Integration with Github Actions
#teste
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Build Application Jar with Gradle
      run: ./gradlew clean build -x test

    - name: Docker Compose Build
      run: docker compose build
    
    - name: Push to Docker Hub Container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/estudando-spring-docker-aws-spring-app:latest ${{ secrets.DOCKER_USERNAME }}/estudando-spring-docker-aws-spring-app:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/estudando-spring-docker-aws-spring-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/estudando-spring-docker-aws-spring-app:latest
